/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'watchId' : bigint, 'quantity' : bigint }
export interface Watch {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'company' : string,
  'isFeatured' : boolean,
  'modelNumber' : string,
  'gender' : string,
  'price' : bigint,
  'images' : Array<Uint8Array>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addToCart' : ActorMethod<[string, bigint, bigint], undefined>,
  'addWatch' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      Array<Uint8Array>,
      boolean,
    ],
    bigint
  >,
  'clearCart' : ActorMethod<[string], undefined>,
  'deleteWatch' : ActorMethod<[bigint], undefined>,
  'getAllWatches' : ActorMethod<[], Array<Watch>>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getCartTotal' : ActorMethod<[string], bigint>,
  'getFeaturedWatches' : ActorMethod<[], Array<Watch>>,
  'getWatch' : ActorMethod<[bigint], [] | [Watch]>,
  'removeFromCart' : ActorMethod<[string, bigint], undefined>,
  'searchWatches' : ActorMethod<[string], Array<Watch>>,
  'updateCartItemQuantity' : ActorMethod<[string, bigint, bigint], undefined>,
  'updateWatch' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      string,
      string,
      Array<Uint8Array>,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];