/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Watch = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'modelNumber' : IDL.Text,
  'gender' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
});
export const CartItem = IDL.Record({
  'watchId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'addWatch' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'clearCart' : IDL.Func([IDL.Text], [], []),
  'deleteWatch' : IDL.Func([IDL.Nat], [], []),
  'getAllWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
  'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
  'getCartTotal' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getFeaturedWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
  'getWatch' : IDL.Func([IDL.Nat], [IDL.Opt(Watch)], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'searchWatches' : IDL.Func([IDL.Text], [IDL.Vec(Watch)], ['query']),
  'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'updateWatch' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Vec(IDL.Nat8)),
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Watch = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'modelNumber' : IDL.Text,
    'gender' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  });
  const CartItem = IDL.Record({ 'watchId' : IDL.Nat, 'quantity' : IDL.Nat });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'addWatch' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'clearCart' : IDL.Func([IDL.Text], [], []),
    'deleteWatch' : IDL.Func([IDL.Nat], [], []),
    'getAllWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
    'getCart' : IDL.Func([IDL.Text], [IDL.Vec(CartItem)], ['query']),
    'getCartTotal' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getFeaturedWatches' : IDL.Func([], [IDL.Vec(Watch)], ['query']),
    'getWatch' : IDL.Func([IDL.Nat], [IDL.Opt(Watch)], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'searchWatches' : IDL.Func([IDL.Text], [IDL.Vec(Watch)], ['query']),
    'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'updateWatch' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Vec(IDL.Nat8)),
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };